repos:
  - hooks:
      - id: cargo-check
      - id: clippy
        args: [ '--all-targets', '--all-features' , '--', '-D', 'warnings' ]
    repo: https://github.com/FeryET/pre-commit-rust
    rev: v1.2.1